<a href="https://colab.research.google.com/github/mayank05942/Using-Python-to-Interact-with-OS/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Creating numpy array

In [ ]:
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [ ]:
# Numpy arrays cannot have elements of different types
# If different data types are present they will be converted into strings ( Unlike Lists)

a = [1,2,3,'mayank',4.5]
b = np.array(a)
b

array(['1', '2', '3', 'mayank', '4.5'], dtype='<U21')

In [ ]:
# The behaviour could be changes if we specify the dtype as int -> will not work for strings
# strings cannot be directly converted into int->     string->float->int
a = [1,2,3,'4',4.5]
b = np.array(a,dtype= float)
b

array([1. , 2. , 3. , 4. , 4.5])

In [ ]:
b = np.ones(3,dtype = int) # deafult: float
b

array([1, 1, 1])

In [ ]:
b = np.zeros(3,dtype = int)
b

array([0, 0, 0])

In [ ]:
# Multi-dim arrays
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.full(3,5) # (dim,fill_value)
b

array([5, 5, 5])

In [ ]:
# Creating a linespace array with a given step size
# np.arange(start,end-1,step)
b = np.arange(2,10,2)
b


array([2, 4, 6, 8])

In [ ]:
# line space -> generate 50 samples between a,b default otherwise specified -> stepsize is automatically calculated
b = np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [ ]:
b = np.linspace(2,10,5)
b

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
b = np.identity(3) # only square indentity matrix
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
b = np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# Generate random values
# Distribution is uniform and is between 0 to 1
b = np.random.rand(3)
b

array([0.25478026, 0.98990748, 0.88520272])

In [ ]:
b = np.random.rand(3,4)
b

array([[0.11191438, 0.97343879, 0.2188234 , 0.23188088],
       [0.63950358, 0.86610548, 0.08716611, 0.48783509],
       [0.71719832, 0.66728875, 0.43516447, 0.07394366]])

In [ ]:
# if we want distribution between a certain range 0-b
# p = np.random.rand(10)*b
b = np.random.rand(5)*10
b

array([2.0376931 , 9.39302999, 5.38493256, 9.07159193, 7.59229673])

#Slicing and Indexing

In [ ]:
a = [1,2,3,4]
b = np.array(a)
print(b.data) # Memory location to the first element of the array (Like pointers in c++)
print(b.shape) # size
print(b.dtype) # type of data inside the array
print(b.strides) # How many bytes to be skipped to move to the next element in the memory

(4,)
int64
(8,)


In [ ]:
a1 = [[1,2,3],[4,5,6],[7,8,9]]
b1 = np.array(a1)
print(b1.data) # Memory location to the first element of the array (Like pointers in c++)
print(b1.shape) # size
print(b1.dtype) # type of data inside the array
print(b1.strides) # How many bytes to be skipped to move to the next element in the memory

(3, 3)
int64
(24, 8)


In [ ]:
# Slicing and indexing is same as of normal 1D-array
# In 2D np array we can do: arr[4,5] which is same as arr[4][5]
print(b1[2,2])
print(b1[2][2])

9
9


In [ ]:
print(b1[0:2,1]) # slicing is different in numpy and normal array, normal array first execute the first part and then second
print(b[0:2][1])

# Slicing inside the array-> Always use a np array not list-> like small square inside the matrix

[2 5]
2


# Maths operations

In [ ]:
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)
print(a)
print(b)

[ 1 11  8  3  6]
[10 17  2  8 17]


In [ ]:
# numpy uses vectorization due to which it can do 4 operations at a time, hence very fast
a = a + 1  # element wise addition of 1
a

array([ 2, 12,  9,  4,  7])

In [ ]:
# element wise addtion to two arrays
# similarly we can do -> {-,*,/,//,**} -> // floor divsion
c = a + b 
c
# no need to run a loop like in normal arrays

array([12, 29, 11, 12, 24])

In [ ]:
print(a.mean())
print(a.max())
print(a.min())
print(a.sum())
print(a.argmax()) # index of max element
print(a.argmin())

6.8
12
2
34
1
0


In [ ]:
# Logical and Relational operations

a > b # element wise check

array([False, False,  True, False, False])

In [ ]:
# AND, OR and NOT operation
print(np.logical_and(a,b))

[ True  True  True  True  True]


#Boolean Indexing

In [48]:
# getting the index of those samples which satisfying some conditions using a boolean array
# extract elements according to a condition
bool_arr = a > 2
print(bool_arr)
new_arr = a[bool_arr] # will return those samples whose index is True
print(a)
new_arr


[False  True  True  True  True]
[ 2 12  9  4  7]


array([12,  9,  4,  7])

In [49]:
# Update elements through slicing
a[:3] = 9
a

array([9, 9, 9, 4, 7])

In [51]:
# Update using condition
a[a>5] = 6
a

array([6, 6, 6, 4, 6])

In [52]:
# Finding the index of those elements which satisfy a given condition
ind = np.where(a == 6)
ind

(array([0, 1, 2, 4]),)

In [53]:
a = np.random.randint(1,30,(5,6))
a

array([[ 1,  6,  4, 15, 18, 17],
       [26, 17, 19,  6,  7, 13],
       [27,  3,  7,  8,  7, 14],
       [12, 18, 24, 11,  9, 12],
       [23, 12, 14, 29, 24,  7]])

In [54]:
a > 20

array([[False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [ True, False, False,  True,  True, False]])

# Broadcasting

In [55]:
# Dealing with arrays with different dimensions
# Broadcastingh describes how numpy will treat arrays with unequal dimensions
# Compatibility conditions for np maths operations
#1- Two arrays have same dim
#2- One of them have 1 in the dim like: (3,3) vs (1,3) - > Broadcasting will work here
# Broadcasting will repeat repeats to make dim compatible -> Done internally
# array will lesser dim is broadcasted to fill the shape
# Learn resize() and reshape()